---
fontsize: 11pt
header-includes:
# - \usepackage{setspace}\onehalfspacing
- \setlength{\abovedisplayskip}{4pt}
- \setlength{\belowdisplayskip}{4pt}
- \setlength{\abovedisplayshortskip}{1pt}
- \setlength{\belowdisplayshortskip}{1pt}
- \usepackage{verbatim}
- \ifdefined\Shaded\renewenvironment{Shaded}{
  \small\begin{tcolorbox}[top=2pt, bottom=0pt, borderline west={3pt}{0pt}{shadecolor},
  interior hidden, frame hidden, enhanced, boxrule=0pt, sharp corners,
  breakable]}{\end{tcolorbox}}\fi
- \usepackage{pgf}\usepackage{pgfplots}\usepackage{tikz}
- \usetikzlibrary{graphs, arrows, automata, shadings}
- \setlength{\floatsep}{0pt}
format:
  pdf:
    documentclass: scrartcl
    geometry: margin=2.4cm, footskip=1cm
    keep-tex: true
execute:
  freeze: auto
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, cache = TRUE,
                      fig.align = "center",
                      fig.width = 4,
                      fig.height = 3)
```

# Proposal: Vaccine resistance or waning immunity?

### Kevin Chen, Zixuan Chen, Jingxuan Fan

\begin{figure}[H]
\caption{Compartmental model of Rella et alia (2021), which modeled Covid-19 epidemic dynamics when the emergence of a vaccine-resistant variant is possible.}
\begin{center}
\begin{tikzpicture}[>= stealth, shorten >= 0pt,
                    auto, node distance=4.5cm, semithick]
\tikzstyle{every state}=[shape=rectangle, draw=black, 
                    semithick, inner sep=1pt, minimum size=1cm]
  \node[state] (S) {$S$};
  \node[state] (Iwt) [right of=S] {$I_{wt}$};
  \node[state] (R)   [right of=Iwt] {$R$};
  \node[state] (Ir)  [below right of=S, node distance=3cm, xshift=1.25cm] {$I_r$};
  \node[state] (D)   [right of=Ir] {$D$};
  \node[state] (V)   [below of=S, node distance=5cm] {$V$};
  \node[state] (IrV) [above right of=V, node distance=2.12cm, yshift=0.25cm] {$I_r^V$};
  \node[state] (RV)  [right of=V, node distance=3cm] {$R^V$};
  \path[->]    (S)   edge node {$\beta$} (Iwt);
  \path[->]    (S)   edge node {$\theta$} (V);
  \path[->]    (Iwt) edge node {$\gamma$} (R);
  \path[->]    (R)   edge [bend right=30] node [yshift=0.55cm] {$\mu$} (S);
  \path[->]    (Iwt) edge [bend right=15] node [yshift=0.25cm,xshift=-0.5cm] {$\delta$} (D);
  \path[->]    (R)   edge [bend left=55] node {$\theta$} (RV);
  \path[->]    (RV)  edge node {$\mu$} (V);
  \path[->]    (V)   edge node {$\beta$} (IrV);
  \path[->]    (IrV) edge node {$\gamma$} (RV);
  \path[->]    (IrV) edge [bend right=25] node {$\delta$} (D);
  \path[->]    (S)   edge node {$\beta$} (Ir);
  \path[->]    (Ir)  edge [bend right=12] node [yshift=-0.35cm, xshift=-1.2cm] {$\gamma$} (R);
  \path[->]    (Ir)  edge [bend right=30] node {$\delta$} (D);
  \path[->]    (Iwt) edge [style=dashed, bend right=5] node [yshift=0.45cm, xshift=-0.4cm] {$p$} (Ir);
\end{tikzpicture}
\end{center}
\end{figure}

\begin{figure}[H]
\caption{Compartmental model of Rella et alia (2021), extended to allow vaccinated individuals to return to being susceptible.}
\begin{center}
\begin{tikzpicture}[>= stealth, shorten >= 0pt,
                    auto, node distance=4.5cm, semithick]
\tikzstyle{every state}=[shape=rectangle, draw=black, 
                    semithick, inner sep=1pt, minimum size=1cm]
  \node[state] (S) {$S$};
  \node[state] (Iwt) [right of=S] {$I_{wt}$};
  \node[state] (R)   [right of=Iwt] {$R$};
  \node[state] (Ir)  [below right of=S, node distance=3cm, xshift=1.25cm] {$I_r$};
  \node[state] (D)   [right of=Ir] {$D$};
  \node[state] (V)   [below of=S, node distance=5cm] {$V$};
  \node[state] (IrV) [above right of=V, node distance=2.12cm, yshift=0.25cm] {$I_r^V$};
  \node[state] (RV)  [right of=V, node distance=3cm] {$R^V$};
  \path[->]    (S)   edge node {$\beta$} (Iwt);
  \path[->]    (S)   edge node {$\theta$} (V);
  \path[->]    (Iwt) edge node {$\gamma$} (R);
  \path[->]    (R)   edge [bend right=30] node [yshift=0.55cm] {$\mu$} (S);
  \path[->]    (Iwt) edge [bend right=15] node [yshift=0.25cm,xshift=-0.5cm] {$\delta$} (D);
  \path[->]    (R)   edge [bend left=55] node {$\theta$} (RV);
  \path[->]    (RV)  edge node {$\mu$} (V);
  \path[->]    (V)   edge node {$\beta$} (IrV);
  \path[->]    (IrV) edge node {$\gamma$} (RV);
  \path[->]    (IrV) edge [bend right=25] node {$\delta$} (D);
  \path[->]    (S)   edge node {$\beta$} (Ir);
  \path[->]    (Ir)  edge [bend right=12] node [yshift=-0.35cm, xshift=-1.2cm] {$\gamma$} (R);
  \path[->]    (Ir)  edge [bend right=30] node {$\delta$} (D);
  \path[->]    (Iwt) edge [style=dashed, bend right=5] node [yshift=0.45cm, xshift=-0.4cm] {$p$} (Ir);
  \path[->]    (V) edge [bend left=30] node {$\omega$} (S);
\end{tikzpicture}
\end{center}
\end{figure}

\begin{figure}[H]
\caption{Compartmental model for capturing waning immunity and incomplete vaccination.}
\begin{center}
\begin{tikzpicture}[>= stealth, shorten >= 0pt,
                    auto, node distance=3.5cm, semithick]
\tikzstyle{every state}=[shape=rectangle, draw=black, 
                    semithick, inner sep=1pt, minimum size=1cm]
  \node[state] (S) {$S$};
  \node[state] (I0) [right of=S] {$I_0$};
  \node[state] (R0) [right of=I0, yshift=1cm] {$R_0$};
  \node[state] (D0)  [right of=I0, yshift=-1cm] {$D$};
  %
  \node[state] (V1) [below of=S, node distance=4cm] {$V_1$};
  \node[state] (I1) [right of=V1] {$I_1$};
  \node[state] (R1) [right of=I1, yshift=1cm] {$R_1$};
  \node[state] (D1) [right of=I1, yshift=-1cm] {$D$};
  %
  \node[state] (V2) [below of=V1, node distance=4cm] {$V_2$};
  \node[state] (I2) [right of=V2] {$I_2$};
  \node[state] (R2) [right of=I2, yshift=1cm] {$R_2$};
  \node[state] (D2) [right of=I2, yshift=-1cm] {$D$};
  %
  \path[->]  (S)  edge node {$\beta$} (I0);
  \path[->]  (V1) edge node {$\beta_1$} (I1);
  \path[->]  (V2) edge node {$\beta_2$} (I2);
  \path[->]  (S)  edge node {$\theta$} (V1);
  \path[->]  (V1) edge node {$\theta$} (V2);
  \path[->]  (V1) edge [bend left=30] node {$\omega$} (S);
  \path[->]  (V2) edge [bend left=45] node {$\omega$} (S);
  %
  \path[->]  (I0) edge node {$\gamma$} (R0);
  \path[->]  (I1) edge node {$\gamma$} (R1);
  \path[->]  (I2) edge node {$\gamma$} (R2);
  %
  \path[->]  (R0) edge [bend right=30] node [yshift=0.65cm] {$\mu$} (S);
  \path[->]  (R1) edge [bend right=30] node [yshift=0.65cm] {$\mu$} (V1);
  \path[->]  (R2) edge [bend right=30] node [yshift=0.65cm] {$\mu$} (V2);
  %
  \path[->]  (I0) edge node {$\delta$} (D0);
  \path[->]  (I1) edge node {$\delta_1$} (D1);
  \path[->]  (I2) edge node {$\delta_2$} (D2);
\end{tikzpicture}
\end{center}
\end{figure}